
# This is a basic workflow to help you get started with Actions

name: CD Prod

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ production ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Build
      uses: actions/checkout@v2
    - name: Build
      run: cd Static-Web-Site-Blazor-WebAssembly.UI && dotnet publish --configuration Release -o app
    - name: Deploy To GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v1.3.0
      with:
        # Git branch where assets will be deployed
        target_branch: master
        build_dir: 'app/Static-Web-Site-Blazor-WebAssembly.UI/dist'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
